### ISSUE TITLE
Max buffer count reached for L1MetadataArray_test

### ISSUE THREAD

**Issue by eszpotanski** [The-OpenROAD-Project/megaboom#42]
`L1MetadataArray_test_generate_abstract` fails with `[ERROR RSZ-0060] Max buffer count reached.` error on newer OpenROAD. CI: https://github.com/The-OpenROAD-Project/megaboom/actions/runs/8708125043/job/23884744619#step:7:4378

This error looks like a problem with OpenROAD itself or the configuration for the build error. It appeared after [Docker image](https://github.com/antmicro/OpenROAD-flow-scripts/pkgs/container/openroad-flow-scripts%2Fubuntu22.04) had been updated - OpenROAD-flow-scripts hash used inside the image: [4ac2d01](https://github.com/antmicro/OpenROAD-flow-scripts/tree/4ac2d011db0a3516f79ee8910eb5fb74e663ef74)

**Comment by oharboe** [comment]
Fixed by https://github.com/The-OpenROAD-Project/megaboom/pull/43

**Comment by oharboe** [comment]
@eszpotanski I merged #43, but there are some fixes required to .github/ folder to reflect that L1MetadataArray_test only tests up to and including place now. CI is still trying to build L1MetadataArray_test_cts and L1MetadataArray_test_cts_make, which don't exist.

Could you create a PR to fix this?

Thanks!
