### ISSUE TITLE
Update megaboom to use v3.0-1132-g5acdf457 and generate artifacts

### ISSUE THREAD

**Issue by jeffng-or** [The-OpenROAD-Project/megaboom#81]
orfs docker image v3.0-1132-g5acdf457 includes the CTS fix as well as PDN update that might reduce the ODB size. Update megaboom to use this version.

Mods to make:

1. Update MODULE.bazel to:

> image = "openroad/orfs:v3.0-1132-g5acdf457",
> sha256 = "c5bdb9be709f3bd8f8ce1448fd5907877285bde39bc4f7ecda46cf2c6ae4cd07",

2. Does MODULE.bazel.lock need to be modified?

3. Run bazel build BoomTile_final to generate artifacts into GCP

**Comment by oharboe** [comment]
After modifying MODULE.bazel, you need to run "bazel mod tidy". This will update MODULE.bazel.lock.

MODULE.bazel.lock is Bazel's way to lock down versions, just like package managers in Python, JavaScript, Scala, etc. do
