### ISSUE TITLE
Document BUILD.bazel

### ISSUE THREAD

**Issue by jeffng-or** [The-OpenROAD-Project/megaboom#88]
For those not familiar with Bazel and/or MegaBoom, it might be helpful to document BUILD.bazel, including:

- Description of the build order
- Description of what each orfs_flow target is doing (e.g. for rams, we want to run placement and CTS, so that we can generate the abstract and go no further)

Other misc questions:

- The orfs_flow targets for the boom_tile_rams and the boom_regflle_rams are both named ram, which might lead to some confusion when discussing them. Also, is it possible to run bazel build on just one ram and how would you specify this?

**Comment by oharboe** [comment]
Yes, you can run subtargets to BoomTile. To find targets, run: 

```
bazel query //:*
```

Example:

```
bazel build //:sdq_17x64_synth
```

**Comment by oharboe** [comment]
The build order is in parallel and based on dependencies... With megaboom I don't know how to represent this tersely...

```
bazel query  --output graph "deps(//:BoomTile_route)"
```

Very long output...

```
digraph mygraph {
  node [shape=box];
  "//:BoomTile_route"
  "//:BoomTile_route" -> "@bazel-orfs//:make.tpl\n@bazel-orfs//:deploy.tpl"
  "//:BoomTile_route" -> "//:BoomTile_cts"
  "//:BoomTile_route" -> "@@bazel-orfs~~orfs_repositories~docker_orfs//:makefile"
  "//:BoomTile_route" -> "@@bazel-orfs~~orfs_repositories~docker_orfs//:openroad"
  "//:BoomTile_route" -> "@@bazel-orfs~~orfs_repositories~docker_orfs//:klayout"
  "//:BoomTile_route" -> "@@bazel-orfs~~orfs_repositories~docker_orfs//:tcl8.6"
  "//:BoomTile_route" -> "@@bazel-orfs~~orfs_repositories~docker_orfs//:opengl"
  "//:BoomTile_route" -> "@@bazel-orfs~~orfs_repositories~docker_orfs//:qt_plugins"
  "//:BoomTile_route" -> "@@bazel-orfs~~orfs_repositories~docker_orfs//:gio_modules"
  "//:BoomTile_cts"
  "//:BoomTile_cts" -> "@bazel-orfs//:make.tpl\n@bazel-orfs//:deploy.tpl"
  "//:BoomTile_cts" -> "//:BoomTile_place"
  "//:BoomTile_cts" -> "@@bazel-orfs~~orfs_repositories~docker_orfs//:makefile"
  "//:BoomTile_cts" -> "@@bazel-orfs~~orfs_repositories~docker_orfs//:openroad"

[hundreds of lines deleted]
```

**Comment by oharboe** [comment]
There's some documentation [here](https://github.com/The-OpenROAD-Project/bazel-orfs?tab=readme-ov-file#stage-targets), with respect to what each target is doing. I don't think that bazel-orfs should do more than point to ORFS for e.g. floorplan, place, cts, etc.

**Comment by oharboe** [comment]
Regarding "The orfs_flow targets for the boom_tile_rams and the boom_regflle_rams are both named ram, which might lead to some confusion when discussing them.", please propose some PRs to make things more clear.

The BUILD.bazel in megaboom could do with some cleanup, it is cobbled together....

Though, I might want to wait until we have CI in place for megaboom before we start changing small stuff like this as it reduces the cost and risk of these "no-op" changes..

**Comment by oharboe** [comment]
See if you can create some pull requests, one specific improvement/concern per PR, and then we can review incremental improvements.

**Comment by oharboe** [comment]
nothing specific enough to be actionable, we want to do a pass to improve docs
